// Historia (lore) de cada monstruo para sus fichas en /monstruos/ (castellano) y /en/monsters/ (inglés).
// Tono: ingenioso y de terror amable; cada historia acaba con por qué quiere ser el Señor de la Noche.
import type { CharacterId } from './characters';

export const LORE: Record<CharacterId, { es: string; en: string }> = {
  vampire: {
    es: 'El Conde lleva cuatro siglos en el mismo castillo, con el mismo ataúd y la misma capa, que ya va por la tercera tintorería que cierra de miedo. Ha visto caer imperios, nacer el ajo en polvo y llegar el wifi a Transilvania. Lo tiene todo… menos el título que su familia perdió en una partida de cartas con un hombre lobo en 1703. Quiere ser el Señor de la Noche para recuperar lo que es suyo y, de paso, que alguien por fin le llame «Excelencia» sin reírse.',
    en: 'The Count has lived in the same castle for four centuries, with the same coffin and the same cape, which has already scared three dry cleaners out of business. He has watched empires fall, garlic powder be invented and wifi reach Transylvania. He has everything… except the title his family lost in a card game against a werewolf in 1703. He wants to be Lord of the Night to win back what is his and, while he is at it, be called “Your Excellency” without anyone giggling.',
  },
  werewolf: {
    es: 'De día es Bernardo, contable, alérgico a los gatos y presidente de su comunidad de vecinos. Las noches de luna llena se convierte en Aullador y el que paga es el sofá. Lleva años pidiendo a la luna que se quede llena para siempre, porque hay que reconocer que como lobo se siente mucho más él mismo. Quiere ser el Señor de la Noche porque, si la noche es suya, la luna llena también… y Bernardo no vuelve a pisar la oficina.',
    en: 'By day he is Bernard, an accountant, allergic to cats and president of his residents’ association. On full-moon nights he turns into Howler, and the sofa pays the price. For years he has begged the moon to stay full forever because, let us be honest, he feels far more himself as a wolf. He wants to be Lord of the Night because if the night is his, so is the full moon… and Bernard never sets foot in the office again.',
  },
  mummy: {
    es: 'Ramsés gobernó Egipto durante treinta años y lleva tres mil durmiendo en una pirámide que, según los folletos, «no tiene ninguna maldición». Le despertó un turista con un selfie-stick y, desde entonces, no ha encontrado su trono, su cetro ni su paciencia. Las vendas aprietan, el desierto le da alergia y los arqueólogos siguen llevándose sus cosas a museos. Quiere ser el Señor de la Noche porque un faraón sin reino es solo un señor muy envuelto.',
    en: 'Ramses ruled Egypt for thirty years and has slept for three thousand in a pyramid that, according to the brochures, “carries no curse whatsoever”. A tourist with a selfie stick woke him up and he has not found his throne, his sceptre or his patience since. The bandages pinch, the desert makes him sneeze and archaeologists keep taking his things to museums. He wants to be Lord of the Night because a pharaoh without a kingdom is just a very well wrapped gentleman.',
  },
  invisible: {
    es: 'La Dama Velada fue la científica que inventó la fórmula de la invisibilidad y la primera en descubrir su único efecto secundario: nadie se acuerda de ti. Ni en las fotos de grupo, ni en los premios, ni en los cumpleaños. Así que decidió que, si no la iban a ver, por lo menos la iban a notar. Quiere ser el Señor de la Noche para que, por una vez, todo el mundo sepa exactamente dónde está… justo detrás de ellos.',
    en: 'The Veiled Lady was the scientist who invented the invisibility formula and the first to discover its only side effect: nobody remembers you. Not in group photos, not at award ceremonies, not on your birthday. So she decided that if they were not going to see her, they would at least feel her. She wants to be Lord of the Night so that, for once, everyone knows exactly where she is… right behind them.',
  },
  zombie: {
    es: 'Paciente Cero fue a urgencias por un mordisquito sin importancia y salió por la ventana tres horas después con hambre de cerebros y una pulsera de hospital que todavía lleva puesta. No recuerda su nombre, pero sí que el médico le dijo «no es contagioso». Desde entonces, cada vez que muerde a alguien, gana un amigo para siempre. Quiere ser el Señor de la Noche porque una horda necesita un líder… y porque, siendo sinceros, es el único que se acuerda de dónde viene el plan.',
    en: 'Patient Zero went to A&E with a tiny little bite and left through the window three hours later, craving brains and still wearing a hospital wristband. He does not remember his name, but he does remember the doctor saying “it is not contagious”. Ever since, every time he bites someone he makes a friend for life. He wants to be Lord of the Night because a horde needs a leader… and, honestly, he is the only one who remembers where the plan started.',
  },
  kthula: {
    es: "K'thula durmió eones en una ciudad hundida, soñando con el día en que los astros se alinearan. Los astros se alinearon un martes, sonó el despertador cósmico y descubrió que el océano estaba lleno de plástico y su ciudad se había convertido en un spot de buceo. Ahora sale de lagos, charcas y piscinas municipales con muy mala cara. Quiere ser el Señor de la Noche para hundir el mundo entero un poquito… lo justo para que vuelva a parecer su casa.",
    en: "K'thula slept for aeons in a sunken city, dreaming of the day the stars would align. They aligned on a Tuesday, the cosmic alarm went off and he found the ocean full of plastic and his city turned into a scuba-diving spot. Now he rises out of lakes, ponds and public swimming pools looking deeply unimpressed. He wants to be Lord of the Night to sink the whole world just a little… enough for it to feel like home again.",
  },
  nightmare: {
    es: 'Pesadilla nació la primera vez que un niño miró debajo de la cama y no vio nada. Desde entonces vive en los sueños ajenos, en el armario entreabierto y en ese ruido de la cocina a las tres de la mañana. Su problema es que la gente ya no duerme: series, móviles, notificaciones… y sin sueño no hay pesadillas. Quiere ser el Señor de la Noche para apagar todas las pantallas del mundo y que, por fin, todos vuelvan a dormir. Profundamente. Con él.',
    en: 'Nightmare was born the first time a child looked under the bed and saw nothing there. Since then it has lived in other people’s dreams, in the half-open wardrobe and in that kitchen noise at three in the morning. Its problem is that people do not sleep any more: series, phones, notifications… and without sleep there are no nightmares. It wants to be Lord of the Night to switch off every screen in the world so that everyone finally goes back to sleep. Deeply. With it.',
  },
  mary: {
    es: 'María Sangrienta vive en todos los espejos del mundo y solo puede salir cuando alguien dice su nombre tres veces en la oscuridad. El problema es que ya nadie lo hace bien: unos se equivocan de nombre, otros se ríen a la segunda y casi todos encienden la linterna del móvil. Lleva siglos atrapada entre reflejos, peinándose una melena que nadie le ha pedido. Quiere ser el Señor de la Noche para que la noche entera sea un espejo… y no tener que esperar a que nadie la llame.',
    en: 'Bloody Mary lives in every mirror in the world and can only come out when someone says her name three times in the dark. The problem is nobody does it properly any more: some get the name wrong, some giggle on the second try and almost everyone turns on their phone torch. She has spent centuries trapped between reflections, combing hair nobody asked about. She wants to be Lord of the Night so that the whole night becomes one big mirror… and she never has to wait to be summoned again.',
  },
  reanimated: {
    es: 'Reanimundo está hecho de siete personas distintas y cada una opina diferente sobre adónde ir. El brazo izquierdo era de un boxeador, la pierna derecha de una bailarina y el cerebro, según la etiqueta, de «alguien muy listo» (la etiqueta mentía). Su creador huyó en cuanto abrió los ojos, así que aprendió todo solo: a andar, a hablar y a atraer rayos sin querer. Quiere ser el Señor de la Noche porque, si manda él, nadie volverá a salir corriendo al verle. Bueno, menos.',
    en: 'Reanimund is made of seven different people, and each one has its own opinion on where to go. The left arm belonged to a boxer, the right leg to a ballerina and the brain, according to the label, to “someone very clever” (the label lied). His creator fled the moment he opened his eyes, so he taught himself everything: walking, talking and attracting lightning by accident. He wants to be Lord of the Night because, if he is in charge, nobody will ever run away screaming at the sight of him again. Well, fewer people.',
  },
  doppy: {
    es: 'Nadie sabe cómo es Doppy de verdad. Ni siquiera Doppy. Ha sido panadero, alcalde, la abuela de alguien y, durante una semana muy rara, el perro de los vecinos. Copiar caras es fácil; lo difícil es acordarse de cuál era la tuya. Quiere ser el Señor de la Noche porque es el único papel que todavía no ha interpretado… y porque, cuando lo consiga, por fin habrá una cara que sea solo suya: la que todos teman.',
    en: 'Nobody knows what Doppy really looks like. Not even Doppy. He has been a baker, a mayor, someone’s grandma and, for one very strange week, the neighbours’ dog. Copying faces is easy; remembering which one was yours is the hard part. He wants to be Lord of the Night because it is the only role he has not played yet… and because, once he gets it, there will finally be a face that is his alone: the one everyone fears.',
  },
  witch: {
    es: 'Hécuba lleva trescientos años removiendo el mismo caldero en el mismo pantano, y la receta todavía no le sale. Le falta un ingrediente: «una noche entera sin interrupciones». Pero siempre aparece un caballero, un inquisidor o un influencer de pantanos buscando contenido. Sus pociones son al azar porque las etiquetas se borraron en el siglo XVIII. Quiere ser el Señor de la Noche para cerrar el pantano a las visitas y terminar, por fin, el estofado.',
    en: 'Hecuba has been stirring the same cauldron in the same swamp for three hundred years and the recipe still will not come out right. It is missing one ingredient: “a whole night without interruptions”. But there is always a knight, an inquisitor or a swamp influencer looking for content. Her potions are random because the labels wore off in the 18th century. She wants to be Lord of the Night to close the swamp to visitors and, at long last, finish the stew.',
  },
  succubus: {
    es: 'Lilith rompió más corazones que nadie en la historia, y no en sentido figurado. Tiene una colección de admiradores que la siguen a todas partes, le escriben poemas y luchan por ella, y está un poco harta de que ninguno sepa cocinar. Dice que el amor es la magia más poderosa; sus enemigos dicen que eso es trampa. Quiere ser el Señor de la Noche porque una reina necesita un reino entero que la adore… y unos cuantos que le hagan la cena.',
    en: 'Lilith has broken more hearts than anyone in history, and not figuratively. She has a collection of admirers who follow her everywhere, write her poems and fight for her, and she is a little tired of none of them knowing how to cook. She says love is the strongest magic; her enemies say that is cheating. She wants to be Lord of the Night because a queen needs a whole kingdom to adore her… and a few people to make dinner.',
  },
  poltergeist: {
    es: 'Poltergeist murió de aburrimiento en una casa muy silenciosa y decidió que la eternidad no iba a ser igual. Lanza sillas, abre grifos, hace volar platos y esconde un calcetín de cada par por pura vocación. Su gran trauma: la familia que vivía en su casa contrató a un cazafantasmas que resultó ser un vecino con un aspirador. Quiere ser el Señor de la Noche para que todas las casas del mundo sean suyas… y hacer ruido sin que nadie le mande callar.',
    en: 'Poltergeist died of boredom in a very quiet house and decided eternity was not going to be like that. It throws chairs, turns on taps, sends plates flying and hides one sock of every pair out of pure vocation. Its great trauma: the family in its house hired a ghostbuster who turned out to be a neighbour with a hoover. It wants to be Lord of the Night so that every house in the world is its own… and it can make noise without anyone telling it to keep it down.',
  },
  tree: {
    es: 'Raíz Negra fue un roble majestuoso hasta que alguien lo eligió para colgar un columpio, otro para grabar un corazón y un tercero para hacer una barbacoa al lado. Tres siglos aguantando fiestas campestres le volvieron rencoroso, retorcido y con muy poca paciencia para los excursionistas. Ahora camina, y eso que los árboles no deberían. Quiere ser el Señor de la Noche para que el bosque recupere la tierra, la sombra y el derecho a pisar a la gente, para variar.',
    en: 'Blackroot was a majestic oak until someone chose it to hang a swing, someone else to carve a heart and a third person to have a barbecue right next to it. Three centuries of picnics made it spiteful, twisted and very short on patience for hikers. Now it walks, even though trees are not supposed to. It wants to be Lord of the Night so the forest can take back the land, the shade and, for a change, the right to step on people.',
  },
  pirate: {
    es: 'Barbasucia hundió su propio barco al intentar robarse a sí mismo un tesoro que había escondido tan bien que no se acordaba de dónde estaba. Se ahogó abrazado al cofre, que resultó estar lleno de cupones caducados. Desde entonces vaga entre lagos y ríos con su tripulación fantasma, que sigue cobrando en doblones imaginarios. Quiere ser el Señor de la Noche para que todo lo que brille en la oscuridad sea botín… y, esta vez, apuntar dónde lo guarda.',
    en: 'Dirtybeard sank his own ship trying to rob himself of a treasure he had hidden so well he could not remember where it was. He drowned hugging the chest, which turned out to be full of expired coupons. Since then he has roamed lakes and rivers with his ghost crew, who still get paid in imaginary doubloons. He wants to be Lord of the Night so that everything that glitters in the dark is loot… and, this time, he will write down where he keeps it.',
  },
  spider: {
    es: 'Aracne tejía los mejores tapices del mundo hasta que se atrevió a decir que eran mejores que los de una diosa. La diosa no lo llevó bien. Ahora tiene ocho patas, ocho ojos y una paciencia infinita para esperar en el centro de su tela. Lo bueno: ya no tiene que comprar hilo. Lo malo: nadie quiere ir a sus exposiciones. Quiere ser el Señor de la Noche para tejer una tela que cubra el mundo… y que, por fin, alguien admita que es una obra maestra.',
    en: 'Arachne wove the finest tapestries in the world until she dared to say they were better than a goddess’s. The goddess did not take it well. Now she has eight legs, eight eyes and endless patience for waiting in the middle of her web. The good part: she never has to buy thread again. The bad part: nobody comes to her exhibitions. She wants to be Lord of the Night to weave a web that covers the whole world… and for someone to finally admit it is a masterpiece.',
  },
  scarecrow: {
    es: 'El Segador pasó cuarenta años quieto en un campo de trigo espantando cuervos, y los cuervos acabaron haciéndose amigos suyos. Un otoño, el granjero lo cambió por un espantapájaros de plástico con luces solares. Mala idea. Ahora el Segador sabe que, si se queda muy quieto, nadie le presta atención… hasta que es demasiado tarde. Quiere ser el Señor de la Noche para que todos los campos del mundo sean suyos y nadie vuelva a jubilarle sin preguntar.',
    en: 'The Harvester stood still in a wheat field for forty years scaring crows, and the crows ended up becoming his friends. One autumn the farmer replaced him with a plastic scarecrow with solar lights. Bad idea. Now the Harvester knows that if he stands very still nobody pays attention… until it is too late. He wants to be Lord of the Night so that every field in the world is his and nobody ever retires him again without asking.',
  },
  demon: {
    es: 'Azufre fue despedido del Infierno por exceso de entusiasmo: quemaba los formularios antes de leerlos. En la Tierra todo le parece frío, húmedo y mal calefactado, y lleva fatal que la gente apague las hogueras «por seguridad». Deja huellas chamuscadas allá donde pisa y una factura de luz astronómica. Quiere ser el Señor de la Noche para subir la temperatura del mundo unos mil grados y demostrar en el Infierno que el que se ha quemado es otro.',
    en: 'Brimstone was fired from Hell for excessive enthusiasm: he burned the forms before reading them. On Earth everything feels cold, damp and badly heated to him, and he hates it when people put out bonfires “for safety reasons”. He leaves scorched footprints wherever he goes and an astronomical electricity bill. He wants to be Lord of the Night to turn the world up a thousand degrees and prove to Hell that someone else got burned.',
  },
  slime: {
    es: 'Baba nació en un laboratorio cuando un becario derramó el café sobre un experimento secreto. Al principio era una mancha en el suelo; ahora es una mancha en el suelo con ambición. Se divide cuando le pegan, se pega cuando la pisan y se lo come todo, incluido el informe que explicaba cómo detenerla. Quiere ser el Señor de la Noche para cubrir el mundo entero de baba verde… y que nadie vuelva a llamarla «eso».',
    en: 'Goo was born in a lab when an intern spilled coffee on a top-secret experiment. At first it was a stain on the floor; now it is a stain on the floor with ambition. It splits when hit, sticks when stepped on and eats everything, including the report explaining how to stop it. It wants to be Lord of the Night to cover the whole world in green goo… and so nobody ever calls it “that thing” again.',
  },
  alien: {
    es: 'El Visitante vino a la Tierra en una misión científica de tres días y lleva setenta años esperando a que le recojan. Ha abducido vacas, granjeros y un autobús escolar entero buscando a alguien que le explique cómo funciona el planeta, sin éxito. Su nave tiene el depósito vacío y la gasolina terrestre le sienta fatal. Quiere ser el Señor de la Noche para mandar sobre el planeta un ratito, encontrar combustible… y escribir en la reseña: «una estrella, gente rara».',
    en: 'The Visitor came to Earth on a three-day research mission and has been waiting seventy years to be picked up. He has abducted cows, farmers and a whole school bus looking for someone to explain how the planet works, without success. His ship is out of fuel and Earth petrol does not agree with it. He wants to be Lord of the Night to run the planet for a little while, find some fuel… and leave a review saying: “one star, weird people”.',
  },
  static: {
    es: 'Interferencia vivía dentro de una tele antigua, en el canal que sale después de que acaben todos los programas. Cuando llegaron las pantallas planas, la tiraron a un contenedor y se quedó sin casa. Desde entonces salta de tele en tele, hipnotiza a quien la mira demasiado y odia profundamente el botón de «saltar intro». Quiere ser el Señor de la Noche para que el mundo entero sea su canal… en directo, sin anuncios y sin mando a distancia.',
    en: 'Interference used to live inside an old television, on the channel that comes on after every programme has finished. When flat screens arrived, the TV was thrown in a skip and she was left homeless. Since then she jumps from TV to TV, hypnotises anyone who stares too long and deeply hates the “skip intro” button. She wants to be Lord of the Night so the whole world becomes her channel… live, with no adverts and no remote control.',
  },
  kappa: {
    es: 'Kappa es un duende del río muy educado: antes de ahogarte, te hace una reverencia. Lleva siglos protegiendo su charca, su cuenco de agua en la cabeza y su colección de pepinos, que es mejor de lo que parece. El problema es que la gente ya no saluda y, claro, él tampoco. Quiere ser el Señor de la Noche para que vuelvan los buenos modales… y que cada río del mundo tenga su ración de pepinos.',
    en: 'Kappa is a very polite river imp: before drowning you, he bows. He has spent centuries guarding his pond, the bowl of water on his head and his cucumber collection, which is better than it sounds. The problem is nobody bows back any more and, naturally, neither does he. He wants to be Lord of the Night to bring good manners back… and to give every river in the world its own supply of cucumbers.',
  },
  reaper: {
    es: 'La Parca lleva toda la eternidad recogiendo almas sin un solo día de vacaciones, sin ascensos y sin que nadie le diga gracias. Hace poco descubrió que los monstruos de esta noche no hay manera de que se mueran del todo, y se le acumula el trabajo. Así que ha decidido cambiar de puesto. Quiere ser el Señor de la Noche para firmar ella misma su primer día libre… y decidir quién trabaja de ahora en adelante.',
    en: 'The Reaper has spent all of eternity collecting souls without a single day off, no promotions and nobody ever saying thank you. Recently she discovered that the monsters out tonight simply refuse to stay dead, and her workload is piling up. So she has decided to change jobs. She wants to be Lord of the Night to sign her own first day off… and decide who does the work from now on.',
  },
  unit: {
    es: 'Legión empezó siendo una sola persona en una fiesta muy aburrida. Se fue sumando gente, luego más gente, y un día ya no había forma de saber dónde acababa uno y empezaba el otro. Ahora piensan a la vez, hablan en plural y votan cada decisión, lo que vuelve las compras del súper muy largas. Quieren ser el Señor de la Noche porque, si todos son Legión, por fin dejarán de discutir… y la próxima fiesta será inolvidable.',
    en: 'Legion started out as a single person at a very boring party. Other people joined in, then more, and one day there was no telling where one ended and the next began. Now they think at the same time, speak in the plural and vote on every decision, which makes grocery shopping take forever. They want to be Lord of the Night because, if everyone is Legion, the arguing will finally stop… and the next party will be unforgettable.',
  },
  necro: {
    es: 'El Nigromante estudió medicina, pero suspendió la parte de «los muertos se quedan muertos». Prefirió especializarse en levantar esqueletos, que no se quejan, no cobran y siempre están disponibles para mover muebles. Su biblioteca de hechizos está ordenada por orden alfabético de huesos. Quiere ser el Señor de la Noche porque cada cementerio es una plantilla en potencia… y tiene grandes planes para todos ellos.',
    en: 'The Necromancer studied medicine but failed the “the dead stay dead” module. He chose to specialise in raising skeletons instead: they do not complain, do not get paid and are always available to move furniture. His spell library is sorted alphabetically by bone. He wants to be Lord of the Night because every graveyard is a potential workforce… and he has big plans for all of them.',
  },
  worm: {
    es: 'Gusarena es tan grande que tardó cien años en enterarse de que había gente encima. Al principio pensaba que las pisadas eran lluvia; luego, que era música. Cuando descubrió que eran turistas haciendo fotos en sus dunas, salió a saludar y todavía no ha parado. Quiere ser el Señor de la Noche para convertir el mundo en un desierto enorme… y poder dormir la siesta sin que le salten encima.',
    en: 'Dune Worm is so big it took a hundred years to notice there were people on top of it. At first it thought the footsteps were rain; then it thought they were music. When it found out they were tourists taking photos on its dunes, it came up to say hello and has not stopped since. It wants to be Lord of the Night to turn the world into one huge desert… and finally have a nap without anyone jumping on it.',
  },
  dino: {
    es: 'Dinozombie se extinguió hace sesenta y cinco millones de años y no le pareció justo. Un meteorito, sin avisar, ¡con lo bien que estaba! Una expedición lo despertó por accidente en la jungla y ahora cambia de forma según el humor: veloz cuando tiene prisa, cabezota cuando le llevan la contraria y con alas cuando quiere hacerse el interesante. Quiere ser el Señor de la Noche para recuperar el planeta que era suyo antes de que llegaran todos estos mamíferos.',
    en: 'Dinozombie went extinct sixty-five million years ago and did not think it was fair. A meteor, no warning, just when things were going so well! An expedition woke it up by accident in the jungle and now it changes shape depending on its mood: fast when it is in a hurry, stubborn when someone argues and winged when it wants to look interesting. It wants to be Lord of the Night to win back the planet that was its own before all these mammals turned up.',
  },
  r800: {
    es: 'R-800 viene del futuro con una misión muy clara, pero en el viaje en el tiempo se le borró la mitad del archivo. Solo recuerda tres palabras: «noche», «señor» y «objetivo». No siente miedo, no se enamora y no entiende los chistes, aunque lleva un registro de cada uno por si acaso. Quiere ser el Señor de la Noche porque, según sus cálculos, es la única forma de cumplir la misión… y de que alguien le explique qué tiene de gracioso un pato.',
    en: 'R-800 comes from the future with a very clear mission, but half the file got wiped during the time jump. It only remembers three words: “night”, “lord” and “target”. It feels no fear, does not fall in love and does not get jokes, although it logs every single one just in case. It wants to be Lord of the Night because, by its calculations, that is the only way to complete the mission… and to get someone to explain what is so funny about a duck.',
  },
  huntress: {
    es: 'La Cazadora fue la mejor de la Orden durante veinte años: estacas, balas de plata, agua bendita, de todo. Un día se dio cuenta de que los monstruos al menos eran sinceros y la Orden, no tanto. Se llevó su ballesta, su experiencia y la llave del almacén de antorchas. Ahora arma a los aldeanos para que se defiendan solos. Quiere ser el Señor de la Noche para acabar con la Orden desde dentro de la noche… y demostrar que el monstruo nunca fue quien ellos decían.',
    en: 'The Huntress was the Order’s best for twenty years: stakes, silver bullets, holy water, the lot. One day she realised that monsters were at least honest and the Order, not so much. She took her crossbow, her experience and the key to the torch storeroom. Now she arms villagers so they can defend themselves. She wants to be Lord of the Night to bring the Order down from inside the night… and prove the monster was never who they said it was.',
  },
  candle: {
    es: 'Cenizo fue la vela de una mansión encantada durante doscientos años. Alumbró bailes, cenas y sesiones de espiritismo, y nadie le dio nunca las gracias: solo le soplaban al irse a dormir. Un día una corriente lo apagó a medias y se le quedó la cara así, derretida de rabia. Ahora camina dejando gotas de cera y decide quién ve y quién no. Quiere ser el Señor de la Noche para ser la única luz del mundo… y que, por fin, nadie se atreva a soplarle.',
    en: 'Cinder was a candle in a haunted mansion for two hundred years. He lit balls, dinners and séances, and nobody ever thanked him: they just blew him out on their way to bed. One day a draught half-snuffed him and his face stayed like that, melted with rage. Now he walks around leaving drops of wax and decides who gets to see and who does not. He wants to be Lord of the Night to be the only light in the world… and so nobody ever dares to blow him out again.',
  },
};
